### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by valireality** [Sven-Bo/merge-txt-files-export-to-xlsm#1]
Which python version did you use?

Because with Python 3.10, i got this error:
```
Traceback (most recent call last):
  File "/root/merge-txt-files-export-to-xlsm/generate_test_results.py", line 20, in <module>
    with xw.App(visible=False) as app:
  File "/usr/local/lib/python3.10/dist-packages/xlwings/main.py", line 279, in __init__
    self.impl = engines.active.apps.add(
AttributeError: 'NoneType' object has no attribute 'apps'
```

Thanks

**Comment by Sven-Bo** [comment]
3.8.5

**Comment by valireality** [comment]
Same error :(

```
python3.8 generate_test_results.py
Traceback (most recent call last):
  File "generate_test_results.py", line 19, in <module>
    with xw.App(visible=False) as app:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/xlwings/main.py", line 279, in __init__
    self.impl = engines.active.apps.add(
AttributeError: 'NoneType' object has no attribute 'apps'
```

**Comment by Sven-Bo** [comment]
Looks like you are running it on Ubuntu.

> xlwings (Open Source) requires an installation of Excel and therefore only works on Windows and macOS. Note that macOS currently does not support UDFs.

https://docs.xlwings.org/en/latest/installation.html
